Hw9
Thefaceless1/SHELEKH_HW pull request #12
Opened 2022-10-30 19:08 UTC by Thefaceless1

Hw9

2022-10-30 21:48 UTC, oromis1508 commented on HW9/task1.ts
> +    }
это 1 должен быть 1 геттер:
геттер, который возвращает символ `symNum` в строке `str`. Если `symNum` больше, чем символов в `str`, возвращает случайный символ

2022-10-30 21:48 UTC, oromis1508 commented on HW9/task1.ts
> +    static changeStr (map:any) {
map:Map<string,string>

2022-10-30 21:51 UTC, oromis1508 commented on HW9/task1.ts
> +        split(map[1][0]).join(map[1][1]);
подразумевает использование цикла, в задании только пример, может быть 3,5,10 элементов в Map

2022-10-30 21:51 UTC, oromis1508 commented on HW9/task1.ts
> +    static sym:string = "s"
класс, принимающий строку (`str`), число (`symNum`) и символ (`sym`), т.е. сделать через конструктор, не статики

2022-10-30 21:59 UTC, oromis1508 commented on HW9/task3.ts
> +            if (!(this.str[i] in Object.fromEntries(collectionSymbols))) collectionSymbols.set(this.str[i], 1);
if (!collectionSymbols.has(this.str[i]))

2022-10-30 21:59 UTC, oromis1508 commented on HW9/task3.ts
> +    static classNum: number = 5
тоже, что с 1, с конструктором

2022-10-30 22:21 UTC, oromis1508 commented on HW9/task3.ts
> +            join("");
такое лучше делать через if-else и с разделение на части, т.к. очень трудно читать и дебажить + неправильно работает в случае с num == 0

2022-10-30 22:24 UTC, oromis1508 requested changes
В основном исправления в плане того, что не совсем по заданию, но есть и немного кроме

2022-10-31 09:30 UTC, Thefaceless1 commented on HW9/task1.ts
> +    static sym:string = "s"
там не написано про конструктор. во втором задании четко написано через конструктор указать

2022-10-31 09:34 UTC, Thefaceless1 commented on HW9/task1.ts
> +    }
![изображение](https://user-images.githubusercontent.com/102432917/198977052-bc9f0780-4b64-44d1-aaaf-7c10c6502eb0.png)
по условию написано что 2 геттера

2022-11-01 08:38 UTC, merged