HW4
Thefaceless1/SHELEKH_HW pull request #2
Opened 2022-10-14 18:48 UTC by Thefaceless1

HW4

2022-10-16 20:59 UTC, oromis1508 commented on HW4/Task15.ts
> +    else continue;
строка не имеет смысла, т.к. в любом случае цикл будет продолжен

2022-10-16 21:04 UTC, oromis1508 commented on HW4/Task16advanced.ts
> +        else;
эта строчка не нужна

2022-10-16 21:32 UTC, oromis1508 commented on HW4/Task16advanced.ts
> +        }
1. Переприсваивать значение для numberOrString на симол или рандомное число не очень хорошая идея. И из-за этого есть дальше ошибка. Тебе нужно первоначальное значение для определения количества попыток и по названию переменной в дальнейшем не сильно понятно, что в ней хранится загаданное число или символ
2. 4 разных if - else не имеют смысла, т.к. в 1 и 2, 3 и 4 попарно выполняются одинаковые действия.
Как можно было бы уменьшить объем кода:
>let numberOrString = readline4.question("Введите строку (от 5 до 15 символов) или число (от 5 до 15):\n");
let numericInput = +numberOrString;
let messageToAsk = "Угадайте букву:\n";
let maxIndex = numberOrString.length > 15 ? 15 : numberOrString.length;
let hiddenValue = numberOrString[Math.round(Math.random()*maxIndex)];
console.clear();
if (!isNaN(numericInput)) {
messageToAsk = 'Угадайте число\n';
maxIndex = numericInput > 15 ? 15 : numericInput ;
hiddenValue = Math.round(Math.random()*(numericInput-1) +1).toString();
}
let attempts = Math.ceil(maxIndex/3);

Дальше всех этих переменных достаточно, чтобы сделать 1 цикл, общий для символа и числа

2022-10-16 21:34 UTC, oromis1508 commented on HW4/Task4.ts
> +const resultTask4 = (someStringTask4.endsWith(".")) ? "Данное предложение закончено" : "В конце предложения не хватает точки" ;
(someStringTask4.endsWith(".")) - внешние скобки здесь не нужны

2022-10-16 21:38 UTC, oromis1508 requested changes
Немного сложновато сделана часть 16 задания, в остальном отлично

2022-10-16 21:41 UTC, oromis1508 commented on HW4/Task16advanced.ts
> +                for (let i = 1; i<=Math.ceil(numberOrString/3); i++){
Здесь та самая ошибка. В numberOrString уже рандомное число, а не максимально возможное

2022-10-17 08:09 UTC, merged

2022-10-17 08:11 UTC, Thefaceless1 commented on HW4/Task15.ts
> +    else continue;
fixed

2022-10-17 08:11 UTC, Thefaceless1 commented on HW4/Task4.ts
> +const resultTask4 = (someStringTask4.endsWith(".")) ? "Данное предложение закончено" : "В конце предложения не хватает точки" ;
fixed

2022-10-17 09:25 UTC, Thefaceless1 commented on HW4/Task16advanced.ts
> +        else;
fixed

2022-10-17 09:25 UTC, Thefaceless1 commented on HW4/Task16advanced.ts
> +        }
fixed

2022-10-17 09:25 UTC, Thefaceless1 commented on HW4/Task16advanced.ts
> +                for (let i = 1; i<=Math.ceil(numberOrString/3); i++){
fixed