HW5
Thefaceless1/SHELEKH_HW pull request #4
Opened 2022-10-17 12:08 UTC by Thefaceless1

HW5

2022-10-20 11:50 UTC, oromis1508 commented on HW5/task6.ts
> +function fooboo (param: any){
1. any не то чтобы нельзя использовать, но используется в редких случаях
2. foo и boo должны быть аргументами функции, (bool: boolean, trueFunc: () => void, falseFunc: () => void)//() => void мб заменено на Function, но лучше указывать какую конкретно функцию ожидаешь

2022-10-20 12:02 UTC, oromis1508 commented on HW5/task5.ts
> +        for (let i = 0 ; i <= difference ; i++) {
переменные difference и i не имеют смысла, можно без них:
>for (let sum = 0 ; a <= b ; a++) {
 sum += a
}
если

2022-10-20 12:13 UTC, oromis1508 commented on HW5/task4advanced.ts
> +            case "%" :{result =firstNumber % secondNumber;console.clear(); return console.log(`Результат: ${result}`);}
Если ты создавал доп. переменную, то имеет смысл console.clear(); return console.log(`Результат: ${result}`); вынести после switch-case. 
Дублирование кода не есть хорошо, его должно быть как можно меньше, если это возможно.

2022-10-20 12:14 UTC, oromis1508 commented on HW5/task4advanced.ts
> +            case "!" :{result =firstNumber+mathOperation+secondNumber;console.clear(); return console.log(`Результат: ${result}`);}// не очень понятно что делать если пользователь выбрал "!"
Здесь описка в условии, этого знака не должно было быть в задании. Как сделал, так пусть и будет

2022-10-20 12:20 UTC, oromis1508 commented on HW5/task4advanced.ts
> +        mathOperation == "-" || mathOperation =="*" || mathOperation == "!" || mathOperation == "/" || mathOperation == "%")) {
Проверку на оператор можно убрать. У тебя для всех операторов в switch-case есть выход из функции через return. В данном случае если убрать else (только оператор, сами строки, которые в else оставить), то при неправильном операторе у тебя функция продолжит выполняться и перейдёт к этим строкам, которые будут после if

2022-10-20 12:21 UTC, oromis1508 commented on HW5/task4.ts
> +    for ( let i of enteredNumber) {
const i

2022-10-20 12:32 UTC, oromis1508 commented on HW5/task2.ts
> +    overpayment += sumCredit * (percentPerYear/100);
Формула будет не такая, т.к. каждый месяц сумма процентов уменьшается. Можно глянуть формулу в интернете, но если самому, без подсказок, то что-то в таком роде:
>const months = countYears * 12;
const paymentPerMonth = sumCredit / months;
for (let i = 1 ; i<=months; i++) {
overpayment += sumCredit * (percentPerYear/100) / 12;
sumCredit -= paymentPerMonth;
}

2022-10-20 12:49 UTC, oromis1508 commented on HW5/task2advanced.ts
> +}
Молодец, что без подсказок из интернета. Как из вариантов, вычислить max и min значения и:
result = max * (min - 1) + max - 1
В интернете можно найти формулу для любых случаев, но это не так интересно

2022-10-20 12:50 UTC, oromis1508 requested changes
Отлично сделано, видно, что стараешься всё делать. Есть немного исправлений

2022-10-21 07:45 UTC, Thefaceless1 commented on HW5/task6.ts
> +function fooboo (param: any){
fixed

2022-10-21 07:46 UTC, Thefaceless1 commented on HW5/task5.ts
> +let sum = 0;
fixed

2022-10-21 07:52 UTC, Thefaceless1 commented on HW5/task5.ts
> +        for (let i = 0 ; i <= difference ; i++) {
fixed

2022-10-21 07:53 UTC, Thefaceless1 commented on HW5/task5.ts
> +    else return a;
fixed

2022-10-21 08:02 UTC, Thefaceless1 commented on HW5/task4advanced.ts
> +            case "%" :{result =firstNumber % secondNumber;console.clear(); return console.log(`Результат: ${result}`);}
fixed

2022-10-21 08:02 UTC, Thefaceless1 commented on HW5/task4advanced.ts
> +            case "!" :{result =firstNumber+mathOperation+secondNumber;console.clear(); return console.log(`Результат: ${result}`);}// не очень понятно что делать если пользователь выбрал "!"
ok

2022-10-21 08:10 UTC, Thefaceless1 commented on HW5/task4.ts
> +    for ( let i of enteredNumber) {
fixed

2022-10-21 08:11 UTC, Thefaceless1 commented on HW5/task1advanced.ts
> +     return (a+b>c && a+c>b && b+c>a) ? true : false;
fixed

2022-10-21 08:22 UTC, Thefaceless1 commented on HW5/task2.ts
> +    overpayment += sumCredit * (percentPerYear/100);
fixed

2022-10-21 08:22 UTC, merged