Hw6
Thefaceless1/SHELEKH_HW pull request #5
Opened 2022-10-21 08:33 UTC by Thefaceless1

HW6

2022-10-23 09:38 UTC, oromis1508 commented on HW6/task1advanced.ts
> +    switch (true){
switch (true) обычно так не используется, да и нет смысла в конструкции switch-case, если у тебя только 2 кейса. Эта конструкция имеет смысл, если есть минимум 3 кейса или 2 кейса и default блок.

2022-10-23 09:39 UTC, oromis1508 commented on HW6/task1advanced.ts
> +        console.clear();
console.clear(); есть в обоих случаях, поэтому стоит его вынести сразу после
else if (!("penalty" in incomingMatchData)){

2022-10-23 09:43 UTC, oromis1508 commented on HW6/task1advanced.ts
> +        resultMatch = `Команда ${teamOne} забила голов: ${goalsTeam1}\nКоманда ${teamTwo} забила голов:${goalsTeam2}\nРезультат: Ничья`;
Эту часть строки также лучше вынести, т.к. она повторяется в 3 местах, потом просто вместо = использовать +=:
resultMatch = `Команда ${teamOne} забила голов: ${goalsTeam1}\nКоманда ${teamTwo} забила голов:${goalsTeam2}\nРезультат: `

2022-10-23 09:44 UTC, oromis1508 commented on HW6/task1advanced.ts
> +        return resultMatch;
Такая же ситуация, return resultMatch; можно вынести в конец функции и использовать 1 раз вместо 4

2022-10-23 09:53 UTC, oromis1508 commented on HW6/task2advanced.ts
> +console.log(Array.isArray(student2) === Array.isArray(student1));
Не является решением, Array.isArray(object) всегда будет возвращать false для любых объектов.
Здесь делается через for-in цикл + если учесть, что количество свойств у объектов может быть разное, то можно использовать Object.keys для проверки их количества

2022-10-23 10:23 UTC, oromis1508 commented on HW6/task4advanced.ts
> +    }
Можно было немного сократить: через for in проходишься по countUsersMoney. Если в countMoneyAfterGettingMoney ключ есть, то прибавляешь, если нет, то countMoneyAfterGettingMoney[key] = value.
Вторым циклом for in пройтись по countMoneyAfterGettingMoney. И там 2 if с оператором in - для покупателей surrenderOfMoneyUser1 и surrenderOfMoneyUser2 и сразу же можно и вывести результат (либо результат записать в новый объект и просто вывести объект после цикла).
У тебя почти так сделано, только for (const i in countMoneyAfterPurchases) 2 раза зачем-то

2022-10-23 10:24 UTC, oromis1508 commented on HW6/task5.ts
> +let iterationsCountTask5 = 0 ;
Можно было заменить эту переменную на Object.keys().length

2022-10-23 10:30 UTC, oromis1508 requested changes
Выполнено очень хорошо. Основное замечание: старайся избегать дублирования кода, т.к. это одна из плохих практик. Если видишь, что у тебя используется одна и та же строка, одна и та же функция, цикл условие и тп, то старайся объединять такие вещи.

2022-10-23 12:51 UTC, oromis1508 commented on HW6/task2.ts
> +}
здесь можно console.log("key1" in objTask2);

2022-10-25 06:43 UTC, merged

2022-10-25 06:43 UTC, Thefaceless1 commented on HW6/task1advanced.ts
> +        console.clear();
fixed

2022-10-25 06:50 UTC, Thefaceless1 commented on HW6/task1advanced.ts
> +        resultMatch = `Команда ${teamOne} забила голов: ${goalsTeam1}\nКоманда ${teamTwo} забила голов:${goalsTeam2}\nРезультат: Ничья`;
fixed

2022-10-25 06:55 UTC, Thefaceless1 commented on HW6/task1advanced.ts
> +        return resultMatch;
fixed

2022-10-25 06:57 UTC, Thefaceless1 commented on HW6/task2.ts
> +}
fixed

2022-10-25 07:10 UTC, Thefaceless1 commented on HW6/task5.ts
> +let iterationsCountTask5 = 0 ;
fixed